# Generated by Django 2.2.26 on 2022-03-27 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='genre',
        ),
    ]
